name: Code Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install torch torchvision pillow streamlit

      - name: Run Semgrep (Static Analysis)
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep.yml  # Use custom config to suppress false positives

      - name: Trivy File System Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."

      - name: Run Bandit (Python Security Linter)
        run: |
          pip install bandit
          bandit -r . -x tests

      # - name: YAML Linting (K8s YAML / GitHub Actions / Helm)
      #   uses: ibiqlik/action-yamllint@v3
